name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  XDEBUG_MODE: coverage

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: action-yarn
      run: yarn && yarn build

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md
    - name: Init test db
      run: php bin/console doctrine:database:create --env=test && php bin/console doctrine:schema:update --force --env=test
    - name: Run test suite
      run: php bin/phpunit
    - name: Push coverage to codacy
      run: export CODACY_PROJECT_TOKEN=fac315782c644ca0a32283fc9b07c493 && bash <(curl -Ls https://coverage.codacy.com/get.sh)
    - name: Generate code coverage report
      run: php bin/phpunit --coverage-html public/coverage
    - name: Commit coverage report
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add public/coverage
        git commit -m 'Update code coverage report'
        git push origin ${{ github.ref }}
