name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  XDEBUG_MODE: coverage

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: action-yarn
      run: yarn && yarn build

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md
    - name: Init test db
      run: php bin/console doctrine:database:create --env=test && php bin/console doctrine:schema:update --force --env=test
    - name: Run test suite
      run: php bin/phpunit
    - name: Push coverage to codacy
      run: export CODACY_PROJECT_TOKEN=fac315782c644ca0a32283fc9b07c493 && bash <(curl -Ls https://coverage.codacy.com/get.sh)
    - name: Generate code coverage report
      run: php bin/phpunit --coverage-html coverage

    - uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        add: 'public/coverage'
        message: 'Add code coverage report'

